Support filtering by resource type, and more focused namespace retrieval.
robusta-dev/krr pull request #48
Opened 2023-05-25 13:59 UTC by mnbbrown

This allows non-admin users on RBAC enforced clusters to run krr.

2023-05-25 13:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/robusta-dev/krr?pullRequest=48) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/robusta-dev/krr?pullRequest=48) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/robusta-dev/krr?pullRequest=48) it.</sub>

2023-05-25 19:07 UTC, LeaveMyYard commented
Hey, @mnbbrown!
Thanks for the PR! I will test it tomorrow.
Could you sign the CLA please (look in the PR messages ^)?

2023-05-29 07:19 UTC, LeaveMyYard requested changes
Great work! Found some space to improvements and left them as comments.

2023-05-29 07:19 UTC, LeaveMyYard commented on robusta_krr/core/integrations/kubernetes.py
> +            for namespace in self.config.namespaces:
Here we are doing a for loop in a blocking manner. Using `asyncio.gather` should give us a performance boost

2023-05-29 07:19 UTC, LeaveMyYard commented on robusta_krr/core/integrations/kubernetes.py
> +
We should add a warning in case filtering by resources ends up in filtering everything, as it might be confusing to user.

2023-05-29 07:19 UTC, LeaveMyYard commented on robusta_krr/core/models/config.py
> +        return v
Maybe to also make those resources case-insensitive by adding `return [res.lower() for res in v]`.
With current implementation `"Deployment"` passed from user in CLI will not make it to show deployments.

2023-05-29 07:19 UTC, LeaveMyYard commented on robusta_krr/core/integrations/kubernetes.py
> +        if self.config.namespaces == "*":
I think here you accidentally lost the logic where `kube-system` is ignored by default (when scanning with `"*"`)

2023-06-01 06:17 UTC, acaire commented on robusta_krr/main.py
> +                    "-n",
```suggestion
                    "-r",
```

2023-06-01 07:16 UTC, LeaveMyYard commented
@mnbbrown I can finish your PR, if you want, but I need you to sign the CLA for that

2023-06-22 07:46 UTC, LeaveMyYard commented
@mnbbrown Hey again! Can you just sign the CLA requested by the bot? I will finish everything else. It will take a few minutes of your time

2023-08-04 08:57 UTC, LeaveMyYard commented
Remade as #122

2023-08-04 08:57 UTC, closed without merging